export default [
  {
    method: 'GET',
    url: '/backend/member/summary?page=0&size=10',
    response: {
      data: [
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
      ],
    },
  },
  {
    method: 'GET',
    url: '/backend/member/summary?page=1&size=10',
    response: {
      data: [
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
      ],
    },
  },
  {
    method: 'GET',
    url: '/backend/member/summary?page=2&size=10',
    response: {
      data: [
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
        {
          code: 'MEM-00001',
          name: 'John Doe',
          email: 'john.doe@gdn-commerce.com',
          phone: '0123456789',
          dob: '2021-01-01',
          gender: 'M',
          profilePicture: 'www.blibli.com/picture/member.jpg',
        },
      ],
    },
  },
];
